name: Deploy new release to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag is pushed
    runs-on: ubuntu-latest
    steps:
    - name: Install Subversion
      run: sudo apt-get update && sudo apt-get install -y subversion
    - name: Checkout code
      uses: actions/checkout@v3
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
